In [18]:
import numpy as np
import pandas as pd

In [19]:
df = pd.read_csv('/content/Attrition.csv')

In [20]:
df.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7

In [21]:
# df.isnull().sum()

In [22]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [23]:
x = df.drop(columns = ['Attrition'])
y = df['Attrition']

In [24]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [25]:
categorical_data = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'Over18', 'OverTime']

In [26]:
x_encoded = pd.get_dummies(x, columns = categorical_data)

In [27]:
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,False,False,True,False,False,False,True,True,False,True
1,49,279,8,1,1,2,3,61,2,2,...,False,True,False,False,False,True,False,True,True,False
2,37,1373,2,2,1,4,4,92,2,1,...,False,False,False,False,False,False,True,True,False,True
3,33,1392,3,4,1,5,4,56,3,1,...,False,True,False,False,False,True,False,True,False,True
4,27,591,2,1,1,7,1,40,3,1,...,False,False,False,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,False,False,False,False,False,True,False,True,True,False
1466,39,613,6,1,1,2062,4,42,2,3,...,False,False,False,False,False,True,False,True,True,False
1467,27,155,4,3,1,2064,2,87,4,2,...,False,False,False,False,False,True,False,True,False,True
1468,49,1023,2,3,1,2065,4,63,2,2,...,False,False,True,False,False,True,False,True,True,False
1469,34,628,8,3,1,2068,2,82,4,2,...,False,False,False,False,False,True,False,True,True,False

In [28]:
lb = LabelEncoder()

In [29]:
y_encoded = lb.fit_transform(y)

In [30]:
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y_encoded, test_size=0.2, random_state=42)

In [32]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,False,False,False,False,True,False,False,True,True,False
727,18,287,5,2,1,1012,2,73,3,1,...,False,True,False,False,False,False,True,True,True,False
254,29,1247,20,2,1,349,4,45,3,2,...,False,False,True,False,True,False,False,True,True,False
1175,39,492,12,3,1,1654,4,66,3,2,...,False,False,False,False,False,True,False,True,True,False
1341,31,311,20,3,1,1881,2,89,3,2,...,False,False,False,False,True,False,False,True,True,False

In [33]:
sc = StandardScaler()

In [34]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.fit_transform(x_test)

In [37]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units = 128, activation='relu', input_dim = x_train_scaled.shape[1]),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units= 64, activation = 'relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
loss_fn =  tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [39]:
learning_rate = 0.001
momentum = 0.9
optimizer = tf.keras.optimizers.SGD(learning_rate = learning_rate,
                                    momentum = momentum, nesterov = True)

In [40]:
model.compile(optimizer = optimizer, loss = loss_fn, metrics = metrics)

In [41]:
model.fit(x_train_scaled,
          y_train,
          epochs= 50,
          batch_size= 8,
          validation_split = 0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7226 - loss: 0.5641 - val_accuracy: 0.7966 - val_loss: 0.4620
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8339 - loss: 0.4482 - val_accuracy: 0.7881 - val_loss: 0.4272
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8475 - loss: 0.3930 - val_accuracy: 0.8220 - val_loss: 0.4030
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8480 - loss: 0.3672 - val_accuracy: 0.8305 - val_loss: 0.3865
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8337 - loss: 0.3992 - val_accuracy: 0.8390 - val_loss: 0.3745
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8486 - loss: 0.3667 - val_accuracy: 0.8305 - val_loss: 0.3682
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8610 - loss: 0.3247 - val_accuracy: 0.8305 - val_loss: 0.3638
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8683 - loss: 0.3244 - val_accuracy: 0.8390 - val_loss: 0.3593
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8472 - loss: 0.3425 - val_accuracy: 0.8136 - val_loss: 0.3576
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8461 - loss: 0.3413 - val_accuracy: 0.8136 - val_loss: 0.3588
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8795 - loss: 0.2997 - val_accuracy: 0.8220 - val_loss: 0.3580
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8731 - loss: 0.2970 - val_accuracy: 0.8051 - val_loss: 0.3606
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8776 - loss: 0.3012 - val_accuracy: 0.8136 - val_loss: 0.3599
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8962 - loss: 0.2746 - val_accuracy: 0.7966 - val_loss: 0.3584
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8711 - loss: 0.3220 - val_accuracy: 0.8136 - val_loss: 0.3605
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8845 - loss: 0.2827 - val_accuracy: 0.8051 - val_loss: 0.3659
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8887 - loss: 0.2898 - val_accuracy: 0.7966 - val_loss: 0.3671
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8879 - loss: 0.2712 - val_accuracy: 0.7966 - val_loss: 0.3660
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9029 - loss: 0.2563 - val_accuracy: 0.7966 - val_loss: 0.3641
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8716 - loss: 0.2858 - val_accuracy: 0.7881 - val_loss: 0.3668
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8917 - loss: 0.2733 - val_accuracy: 0.8051 - val_loss: 0.3720
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8986 - loss: 0.2641 - val_accuracy: 0.8051 - val_loss: 0.3705
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9084 - loss: 0.2463 - val_accuracy: 0.8136 - val_loss: 0.3774
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9039 - loss: 0.2413 - val_accuracy: 0.8051 - val_loss: 0.3789
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9017 - loss: 0.2396 - val_accuracy: 0.7966 - val_loss: 0.3852
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8934 - loss: 0.2407 - val_accuracy: 0.8051 - val_loss: 0.3913
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8907 - loss: 0.2571 - val_accuracy: 0.7966 - val_loss: 0.3882
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8915 - loss: 0.2740 - val_accuracy: 0.7966 - val_loss: 0.3894
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8852 - loss: 0.2669 - val_accuracy: 0.7966 - val_loss: 0.3909
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9204 - loss: 0.2185 - val_accuracy: 0.7966 - val_loss: 0.3947
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9284 - loss: 0.1933 - val_accuracy: 0.7966 - val_loss: 0.3969
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8835 - loss: 0.2710 - val_accuracy: 0.7966 - val_loss: 0.4026
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9022 - loss: 0.2326 - val_accuracy: 0.7966 - val_loss: 0.4041
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8943 - loss: 0.2328 - val_accuracy: 0.7966 - val_loss: 0.4120
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9065 - loss: 0.2109 - val_accuracy: 0.7966 - val_loss: 0.4129
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9041 - loss: 0.2315 - val_accuracy: 0.7966 - val_loss: 0.4202
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9243 - loss: 0.2010 - val_accuracy: 0.7966 - val_loss: 0.4195
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9287 - loss: 0.2091 - val_accuracy: 0.7966 - val_loss: 0.4185
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9272 - loss: 0.1820 - val_accuracy: 0.7966 - val_loss: 0.4235
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9311 - loss: 0.1969 - val_accuracy: 0.7966 - val_loss: 0.4284
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9086 - loss: 0.2175 - val_accuracy: 0.7966 - val_loss: 0.4233
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9283 - loss: 0.1784 - val_accuracy: 0.7881 - val_loss: 0.4227
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8986 - loss: 0.2172 - val_accuracy: 0.7966 - val_loss: 0.4281
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9114 - loss: 0.2107 - val_accuracy: 0.7966 - val_loss: 0.4333
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1871 - val_accuracy: 0.7966 - val_loss: 0.4309
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9310 - loss: 0.1751 - val_accuracy: 0.7966 - val_loss: 0.4389
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9398 - loss: 0.1703 - val_accuracy: 0.7881 - val_loss: 0.4392
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9228 - loss: 0.1801 - val_accuracy: 0.7881 - val_loss: 0.4492
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9127 - loss: 0.1926 - val_accuracy: 0.8051 - val_loss: 0.4491
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9176 - loss: 0.1989 - val_accuracy: 0.8136 - val_loss: 0.4567

In [42]:
loss, accuracy = model.evaluate(x_test_scaled,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3933

In [43]:
print(loss, accuracy)

0.40328139066696167 0.853741466999054